# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 242b667
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_date: '2022'
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
package_name: hyperloglog
project_description: A hyperloglog implementation in Rust.
project_name: hyperloglog
project_type: lib
repository_name: rust-hyperloglog
repository_namespace: vivienm
repository_provider: github.com
